update for winter 2022 specs

diff --git a/HW2/combine b/HW2/combine
--- a/HW2/combine
+++ b/HW2/combine
@@ -1,17 +1,16 @@
-#Lillian Tatka
-#HW2 Q 3
-#4/20/21 (1 day late)
-
 #!/bin/bash
+
+#Lillian Tatka
+#1/26/2022
 
 # Check for minimum number of args
 if [ $# -lt 2 ]; then
-  echo "Error: too few args" 1>&2; exit 1
+  echo "Usage: combine outputfilename [inputfilename...]" 1>&2; exit 1
 fi
 
-# Check if file exists
+# Check if output file exists
 if [ -e "$1" ]; then
-  echo "Error: first file exists" 1>&2; exit 1
+  echo "Error: Output file should not exist" 1>&2; exit 1
 fi
 
 FILE_OUT="$1"
@@ -19,6 +18,7 @@ FILE_OUT="$1"
 # Adjust indices 
 shift
 
+# Get contents of each input file and write them to the output file
 cat "$@" > "$FILE_OUT" 2>&1
 
 exit 0
diff --git a/HW2/spellcheck b/HW2/spellcheck
--- a/HW2/spellcheck
+++ b/HW2/spellcheck
@@ -1,51 +1,60 @@
 #Lillian Tatka
-#HW2 Q4
-# 4/20/2021  1 day late)
+#1/26/2022 
 
 #!/bin/bash
 
 # Check for correct number of args:
-if [ $# -ne 1 ]; then
-  echo "Error: only 1 argument allowed." 1>&2; exit 1
+
+# No file supplied:
+if [ $# -eq 0 ]; then
+     echo "Usage: spellcheck [inputfilename]" 1>&2; exit 1
 fi
 
-# Check for file validity:
-if [ ! -f $1 ]; then
-  echo "Error: invalid file." 1>&2; exit 1
-fi
 
-touch tempWords
-sed 's/ /\n/g' "$1" > tempWords
-sed -i 's/[[:punct:]]//g' tempWords
+
+
+#touch tempWords
+#sed 's/ /\n/g' "$1" > tempWords
+#sed -i 's/[[:punct:]]//g' tempWords
 
 if [ -e "$1.spelling" ];then
     echo spellcheck replacing "$1.spelling" file
     rm "$1.spelling"
 fi
 
-touch "$1.spelling"
+# Go though each argument (file)
+while [ $# -gt 0 ]; do
 
-while read -r line;
-do
-    if [ "$line" ];
-    then
-	if ! grep -q ^"$line"$ /usr/share/dict/words;
-	then
-	    echo "$line" >> "$1.spelling"
-	fi
-    fi  
-done < tempWords
+    # Check if file exists:
+    if [ ! -f $1 ]; then
+        echo "Error: $1 does not exist --skipping" 1>&2
+    fi
 
-rm tempWords
+    # Check if inputfile.spelling exists:
+    if [ ! -f "$1.spelling" ]; then
+        echo "Creating $1.spelling..."
+    else
+        echo "Replacing $1.spelling..."
+    fi
+    touch "$1.spelling"
+    
+    
+    while read -r line; do
+        for word in $line; do
+            if ! grep -qi ^"$word"$ /usr/share/dict/words; then
+	        echo "$word" >> "$1.spelling"
+            fi
+	done
+    done < "$1"
 
-nWords=$(wc -l < "$1.spelling")
-nUnique=$(sort "$1.spelling" | uniq | wc -l)
+    nWords=$(wc -l < "$1.spelling")
+    nUnique=$(sort "$1.spelling" | uniq | wc -l)
 
-echo spellcheck found $nWords spelling errors, output to file "$1.spelling"
-echo $nUnique of the words are unique
+    echo spellcheck found $nWords spelling errors, output to file "$1.spelling"
+    echo $nUnique of the words are unique
+    shift
+done
 
 exit 0
 
-#while read line; do
-#  for word in $line; do
-#    grep w
+
